### ISSUE TITLE
A state of current documentation

### ISSUE THREAD

**Issue by F5OEO** [openaps/openomni#48]
- Status response is not completely understood (https://github.com/openaps/openomni/wiki/Status-response-1D)

As soon as this is the most important information about POD, it could be good to dig in the fields.

- Documentation could be reorganized for an easy tree access
(like https://github.com/openaps/openomni/wiki/Protocol)

- Use issue to inform current analysis ?

**Comment by Lytrix** [comment]
Hi FSOEO, 

Good idea to reorganise the Wiki, we've done that and with the use of the Projects flow, we can now use issues to inform the current analysis on each message. Can you try to add/move issues on the projects page as a non team member to test?

**Comment by Lytrix** [comment]
Wiki reorganised with help of many participants.
