### ISSUE TITLE
Put an empty `__init__.py` file in the rfcatomni/openomn directory

### ISSUE THREAD

**Issue by yeagerm** [openaps/openomni#63]
Need to put an empty `__init__.py` file in the rfcatomni/openomni directory so that  it is properly recognized as a python package directory. Useful for virtual python environments like Virualenv and Anaconda distributions. Can use:
`pip install -e .` rather than `pip install -e . --process-dependency-links` as outlined in the installation instructions for the RFCAT https://github.com/openaps/openomni/tree/master/rfcatomni

http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html#the-missing-init-py-trap

**Comment by Lytrix** [comment]
Good catch, Thanks for the PR! I've changed the readme.
